name: "juntoseguros"
services:
  elasticsearch:
    build:
      context: Docker/Elastic/
      args:
        ELK_VERSION: $ELK_VERSION
    image: elasticsearch
    container_name: elasticsearch
    volumes:
      - type: bind
        source: ./Docker/Elastic/config/elasticsearch.yml
        target: /usr/share/Elastic/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/Elastic/data
    ports:
      - "${ELASTIC_PORT}:9200"
    environment:
      HTTP_HOST: ${HTTP_HOST}
      NETWORK_HOST: ${NETWORK_HOST}
      NODE_SCALE: ${NODE_SCALE}
      CLUSTER_NAME: ${CLUSTER_NAME}
      discovery.type: ${NODE_SCALE}
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    mem_limit: ${MEM_LIMIT}
    networks:
      - js_env

  kibana:
    build:
      context: Docker/Kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    image: kibana
    container_name: kibana
    volumes:
      - type: bind
        source: ./Docker/Kibana/config/kibana.yml
        target: /usr/share/Kibana/config/kibana.yml
        read_only: true
    environment:
      KIBANA_SERVER_NAME: kibana
      SERVER_HOST: ${KIBANA_SERVER_HOST}
      ELASTIC_SERVER: http://elasticsearch:${ELASTIC_PORT}
    ports:
      - "${KIBANA_PORT}:5601"
    mem_limit: ${MEM_LIMIT}
    depends_on:
      - elasticsearch
    networks:
      - js_env

  logstash:
    build:
      context: Docker/Logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    image: logstash
    container_name: logstash
    volumes:
      - type: bind
        source: ./Docker/Logstash/config/logstash.yml
        target: /usr/share/Logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./Docker/Logstash/pipeline
        target: /usr/share/Logstash/pipeline
        read_only: true
    command: logstash -f /usr/share/Logstash/pipeline/logstash.conf  
    ports:
      - "${LOGSTASH_PORT}:5044"
    mem_limit: ${MEM_LIMIT}
    environment:
      ELASTIC_SERVER: "http://elasticsearch:${ELASTIC_PORT}"

    depends_on:
      - elasticsearch
    networks:
      - js_env

  jaeger:
    build:
      context: Docker/Jaeger/
    image: jaeger-tracing
    container_name: jaeger
    ports:
     - "${JAEGER_PORT}:16686"
    networks:
      - js_env

  otelcollector:
    build:
      context: Docker/OTELCollector/
    image: otel-collector
    container_name: otelcollector
    volumes:
      - type: bind
        source: ./Docker/OTELCollector/config/otel-collector.yml
        target: /usr/share/OTELCollector/config/otel-collector.yml
        read_only: true
    command: [ "--config=/usr/share/OTELCollector/config/otel-collector.yml" ]
    ports:
     - "${OTELCOLLECTOR_GRPC_PORT}:4317"
     - "${OTELCOLLECTOR_HTTP_PORT}:4318"
    mem_limit: ${MEM_LIMIT}
    depends_on:
     - jaeger
    networks:
      - js_env
  
  mssqlserver:
    container_name: mssqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Developer' 
      MSSQL_SA_PASSWORD: '${SQLSERVER_SA_PASSWORD}'
    ports: 
      - "${SQLSERVER_PORT}:1433"
    volumes:
      - ./DockerAppFiles/SQLServer/log:/var/opt/mssql/log
      - ./DockerAppFiles/SQLServer/data:/var/opt/mssql/data
      - ./DockerAppFiles/SQLServer/secrets:/var/opt/mssql/secrets
    networks:
      - js_env
  
  mssqltools:
    container_name: mssqltools
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssqlserver
    volumes:
      - ./Docker/MSTools/init/JuntoSegurosOnboarding_Creation.sql:/tmp/JuntoSegurosOnboarding_Creation.sql
      - ./Docker/MSTools/init/JuntoSegurosOnboarding_Insertions.sql:/tmp/JuntoSegurosOnboarding_Insertions.sql
      - ./Docker/MSTools/init/init-juntoseguros_onboarding.sh:/tmp/init-juntoseguros_onboarding.sh
    command: /bin/bash ./tmp/init-juntoseguros_onboarding.sh
    networks:
      - js_env
  
  # redis:
  #   build:
  #     context: Docker/Redis/
  #   image: redis
  #   container_name: redis
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   ports:
  #     - "${REDIS_PORT}:6379"
  #   mem_limit: ${MEM_LIMIT}
  #   networks:
  #     - js_env

  mongo:
    build:
      context: Docker/Mongo/
    image: mongo
    container_name: mongo
    volumes:
      - type: bind
        source: ./Docker/Mongo/config/mongo.yml
        target: /usr/share/Mongo/config/mongo.yml
        read_only: true
      - type: volume
        source: mongo
        target: /usr/share/Mongo/data/db
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    mem_limit: ${MEM_LIMIT}
    networks:
      - js_env

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./DockerAppFiles/RabbitMQ/data/:/var/lib/rabbitmq/
        - ./DockerAppFiles/RabbitMQ/log/:/var/log/rabbitmq
    networks:
        - js_env
  
  onboarding.command.api:
    image: onboarding-command-api
    build:
      context: .
      dockerfile: src/JuntoSeguros.Onboarding.Command.API/Dockerfile
    environment:
      "ASPNETCORE_HTTP_PORTS": "8080"
      "ASPNETCORE_ENVIRONMENT": "Docker"
    ports:
       - 32804:8080
    depends_on:
       - rabbitmq
    networks:
       - js_env
  
  onboarding.query.api:
    image: onboarding-query-api
    build:
      context: .
      dockerfile: ./src/JuntoSeguros.Onboarding.Query.API/Dockerfile
    environment:
      "ASPNETCORE_HTTP_PORTS": "8080"
      "ASPNETCORE_ENVIRONMENT": "Docker"
    ports:
       - 32805:8080
    depends_on:
       - rabbitmq
    networks:
       - js_env
  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:8.14.0
  #   container_name: filebeat
  #   volumes:
  #     - type: bind
  #       source: ./Filebeat/filebeat.yml
  #       target: /usr/share/Filebeat/filebeat.yml
  #       read_only: true
  #     - type: bind
  #       source: ./Filebeat/test.log
  #       target: /usr/share/Filebeat/test.log
  #       read_only: true
  #   # command: filebeat -e -c /usr/share/Filebeat/filebeat.yml
  #   environment:
  #     ELASTICSEARCH_HOSTS: http://elasticsearch:${ELASTIC_PORT}
  #   depends_on:
  #     - logstash
  #   networks:
  #     - juntoseguros

volumes:
  elasticsearch:
    name: elasticsearch
  mongo:
    name: mongo

networks:
  js_env:
    driver: bridge